#
#Fri Jun 26 23:54:32 UTC 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[remote-allow-origins\=*, --start-maximized, --no-sandbox, --disable-dev-shm-usage, --incognito], extensions\=[]}
